DROP TABLE IF EXISTS ROLE;

CREATE TABLE ROLE (
    ROLE_ID   SMALLINT NOT NULL AUTO_INCREMENT UNIQUE,
    ROLE_NAME VARCHAR(64) NOT NULL UNIQUE,
    PRIMARY KEY (ROLE_ID)
);

INSERT INTO ROLE 
    (ROLE_NAME)
VALUES
    ('User'),
    ('Administrator');