DROP TABLE IF EXISTS USER;

CREATE TABLE USER (
    USER_ID                   CHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
    USER_NAME                 VARCHAR(64) NOT NULL,
    USER_EMAIL                VARCHAR(256) NOT NULL UNIQUE CHECK (USER_EMAIL REGEXP '^[A-Z0-9._%-\+]+@[A-Z0-9._%-]+\.[A-Z]{2,4}$'),
    USER_PASSWORD             VARCHAR(256) NOT NULL,
    ROLE_ID                   SMALLINT NOT NULL,
    USER_CREATED_DATE         DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    USER_LOGIN_DATE           DATETIME,
    USER_PASSWORD_CHANGES     INT NOT NULL DEFAULT 0,
    USER_PASSWORD_CHANGE_DATE DATETIME,
    USER_ARCHIVED             BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (USER_ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ROLE_ID)
);