CREATE TABLE `CONTENT` (
    `CONTENT_ID`                    SERIAL,
    `CONTENT_UUID`                  CHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
    `CONTENT_TITLE`                 VARCHAR(256) NOT NULL,
    `CONTENT_DESCRIPTION`           TINYTEXT NOT NULL,
    `CONTENT_BODY`                  LONGTEXT NOT NULL,
    `USER_ID`                       BIGINT UNSIGNED NOT NULL,
    `CONTENT_CREATED_DATETIME`      DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `CONTENT_LAST_UPDATED_DATETIME` DATETIME,
    `CONTENT_ARCHIVED`              BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`CONTENT_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`)
);