CREATE TABLE `FILE` (
    `FILE_ID`                    SERIAL,
    `FILE_UUID`                  CHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
    `FILE_TITLE`                 VARCHAR(256) NOT NULL,
    `FILE_DESCRIPTION`           TEXT NOT NULL,
    `FILE_MIME_TYPE`             VARCHAR(256) NOT NULL,
    `FILE_BYTES`                 LONGBLOB NOT NULL,
    `USER_ID`                    BIGINT UNSIGNED NOT NULL,
    `FILE_CREATED_DATETIME`      DATETIME NOT NULL,
    `FILE_LAST_UPDATED_DATETIME` DATETIME,
    `FILE_ARCHIVED`              BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (`FILE_ID`),
    FOREIGN KEY (`USER_ID`) REFERENCES `USER`(`USER_ID`)
);