DROP TABLE IF EXISTS CONTENT;

CREATE TABLE CONTENT (
    CONTENT_ID           CHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
    CONTENT_TITLE        VARCHAR(256) NOT NULL,
    CONTENT_DESCRIPTION  TEXT NOT NULL,
    CONTENT_BODY         TEXT NOT NULL,
    USER_ID              CHAR(36) NOT NULL,
    CONTENT_CREATED_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONTENT_UPDATED_DATE DATETIME,
    CONTENT_ARCHIVED     BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (CONTENT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);