DROP TABLE IF EXISTS FILE;

CREATE TABLE FILE (
    FILE_ID           CHAR(36) NOT NULL UNIQUE DEFAULT (UUID()),
    FILE_TITLE        VARCHAR(256) NOT NULL,
    FILE_DESCRIPTION  TEXT NOT NULL,
    FILE_MIME_TYPE    VARCHAR(256) NOT NULL,
    FILE_BYTES        BLOB NOT NULL,
    USER_ID           CHAR(36) NOT NULL,
    FILE_CREATED_DATE DATETIME NOT NULL,
    FILE_UPDATED_DATE DATETIME,
    FILE_ARCHIVED     BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (FILE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID)
);