DROP TABLE IF EXISTS PERMISSIONS;

CREATE TABLE PERMISSIONS (
    USER_ID                 CHAR(36) NOT NULL,
    CONTENT_ID              CHAR(36),
    FILE_ID                 CHAR(36),
    PERMISSIONS_READABLE    BOOLEAN NOT NULL DEFAULT TRUE,
    PERMISSIONS_WRITEABLE   BOOLEAN NOT NULL DEFAULT FALSE,
    PERMISSIONS_ARCHIVEABLE BOOLEAN NOT NULL DEFAULT FALSE,
    PERMISSIONS_DELETEABLE  BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT UNIQUE (USER_ID, CONTENT_ID, FILE_ID),
    CONSTRAINT CHECK ((CONTENT_ID IS NOT NULL AND FILE_ID IS NULL) OR (CONTENT_ID IS NULL AND FILE_ID IS NOT NULL)),
    PRIMARY KEY (USER_ID, CONTENT_ID, FILE_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (CONTENT_ID) REFERENCES CONTENT(CONTENT_ID),
    FOREIGN KEY (FILE_ID) REFERENCES FILE(FILE_ID)
);