DROP TABLE IF EXISTS AUDIT;

CREATE TABLE AUDIT (
    AUDIT_ID          BIGINT NOT NULL UNIQUE AUTO_INCREMENT,
    AUDIT_DESCRIPTION TEXT NOT NULL,
    USER_ID           CHAR(36) NOT NULL,
    CONTENT_ID        CHAR(36),
    FILE_ID           CHAR(36),
    AUDIT_DATE        DATETIME NOT NULL,
    AUDIT_ACTION      TEXT NOT NULL,
    CONSTRAINT CHECK ((CONTENT_ID IS NOT NULL AND FILE_ID IS NULL) OR (CONTENT_ID IS NULL AND FILE_ID IS NOT NULL)),
    PRIMARY KEY (AUDIT_ID),
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    FOREIGN KEY (CONTENT_ID) REFERENCES CONTENT(CONTENT_ID),
    FOREIGN KEY (FILE_ID) REFERENCES FILE(FILE_ID)
);